
package com.java.ws.tomcat;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "CalculatorIfc", targetNamespace = "http://tomcat.ws.java.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface CalculatorIfc {


    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "add", targetNamespace = "http://tomcat.ws.java.com/", className = "com.java.ws.tomcat.Add")
    @ResponseWrapper(localName = "addResponse", targetNamespace = "http://tomcat.ws.java.com/", className = "com.java.ws.tomcat.AddResponse")
    public int add(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        int arg1);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns float
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "divide", targetNamespace = "http://tomcat.ws.java.com/", className = "com.java.ws.tomcat.Divide")
    @ResponseWrapper(localName = "divideResponse", targetNamespace = "http://tomcat.ws.java.com/", className = "com.java.ws.tomcat.DivideResponse")
    public float divide(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        int arg1);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "sub", targetNamespace = "http://tomcat.ws.java.com/", className = "com.java.ws.tomcat.Sub")
    @ResponseWrapper(localName = "subResponse", targetNamespace = "http://tomcat.ws.java.com/", className = "com.java.ws.tomcat.SubResponse")
    public int sub(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        int arg1);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "multiply", targetNamespace = "http://tomcat.ws.java.com/", className = "com.java.ws.tomcat.Multiply")
    @ResponseWrapper(localName = "multiplyResponse", targetNamespace = "http://tomcat.ws.java.com/", className = "com.java.ws.tomcat.MultiplyResponse")
    public int multiply(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        int arg1);

}
